apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: openshift-disconnected-channel
  namespace: open-cluster-management
spec:
  type: GitHub
  pathname: https://github.com/sacharya/acm-labs.git
